export const natures = [
    {name: 'nature', value: 'adamant', label: 'Adamant'},
    {name: 'nature', value: 'bashful', label: 'Bashful'},
    {name: 'nature', value: 'bold', label: 'Bold'},
    {name: 'nature', value: 'brave', label: 'Brave'},
    {name: 'nature', value: 'calm', label: 'Calm'},
    {name: 'nature', value: 'careful', label: 'Careful'},
    {name: 'nature', value: 'docile', label: 'Docile'},
    {name: 'nature', value: 'gentle', label: 'Gentle'},
    {name: 'nature', value: 'hardy', label: 'Hardy'},
    {name: 'nature', value: 'hasty', label: 'Hasty'},
    {name: 'nature', value: 'impish', label: 'Impish'},
    {name: 'nature', value: 'lax', label: 'Lax'},
    {name: 'nature', value: 'lonely', label: 'Lonely'},
    {name: 'nature', value: 'mild', label: 'Mild'},
    {name: 'nature', value: 'modest', label: 'Modest'},
    {name: 'nature', value: 'naive', label: 'Naive'},
    {name: 'nature', value: 'naughty', label: 'Naughty'},
    {name: 'nature', value: 'quiet', label: 'Quiet'},
    {name: 'nature', value: 'quirky', label: 'Quirky'},
    {name: 'nature', value: 'rash', label: 'Rash'},
    {name: 'nature', value: 'relaxed', label: 'Relaxed'},
    {name: 'nature', value: 'sassy', label: 'Sassy'},
    {name: 'nature', value: 'serious', label: 'Serious'},
    {name: 'nature', value: 'timid', label: 'Timid'},
];