import { regionalTeam_02_05_2023, regionalTeam_01_08_2023 } from './regionalsWinningTeams';

export const regional_02_05_2023 = {
    top_16: [
        {name:'Emilio Forbes',score:2},
        {name:'Allan Martinez',score:0},
        {name:'Wolfe Glick',score:2},
        {name:'Aditya Sumramanian',score:0},
        {name:'George Tifverman',score:1},
        {name:'James Evans',score:2},
        {name:'Kyle Livinghouse',score:0},
        {name:'Tyler Webb',score:2},
        {name:'Brendan Zheng',score:0},
        {name:'Ashton Cox',score:2},
        {name:'Johathan Melendez',score:1},
        {name:'Carson Confer',score:2},
        {name:'Brian Collins',score:2},
        {name:'Arbin Tumaneng',score:1},
        {name:'Yichun Wu',score:0},
        {name:'Chuppa Cross IV',score:2},
    ],
    top_8: [
        {name:'Emilio Forbes',score:0},
        {name:'Wolfe Glick',score:2},
        {name:'James Evans',score:2},
        {name:'Tyler Webb',score:1},
        {name:'Ashton Cox',score:2},
        {name:'Carson Confer',score:1},
        {name:'Brian Collins',score:0},
        {name:'Chuppa Cross IV',score:2},
    ],
    top_4: [
        {name:'Wolfe Glick',score:2},
        {name:'James Evans',score:0},
        {name:'Ashton Cox',score:2},
        {name:'Chuppa Cross IV',score:0},
    ],
    top_2: [
        {name:'Wolfe Glick',score:2},
        {name:'Ashton Cox',score:1},
    ],
    winner: 'Wolfe Glick',
    winningTeam: regionalTeam_02_05_2023,
}

export const regional_01_08_2023 = {
    top_16: [
        {name:'Emilio Forbes',score:0},
        {name:'Ezequiel Cordero',score:0},
        {name:'Angel Miranda',score:0},
        {name:'Chuppa Cross IV',score:0},
        {name:'Alberto Lara',score:0},
        {name:'Giovanni Cischke',score:0},
        {name:'Marco Maritnez',score:0},
        {name:'Jeudy Azzarelli',score:0},
        {name:'Gavin Michaels',score:0},
        {name:'James Evans',score:0},
        {name:'Jiseok Lee',score:0},
        {name:'Wolfe Glick',score:0},
        {name:'Giovanni Costa',score:0},
        {name:'Zach Carlson',score:0},
        {name:'Aaron Brok',score:0},
        {name:'Brady Smith',score:0},
    ],
    top_8: [
        {name:'Emilio Forbes',score:0},
        {name:'Chuppa Cross IV',score:2},
        {name:'Giovanni Cischke',score:0},
        {name:'Jeudy Azzarelli',score:2},
        {name:'James Evans',score:0},
        {name:'Jiseok Lee',score:2},
        {name:'Giovanni Costa',score:1},
        {name:'Aaron Brok',score:2},
    ],
    top_4: [
        {name:'Chuppa Cross IV',score:2},
        {name:'Jeudy Azzarelli',score:1},
        {name:'Jiseok Lee',score:2},
        {name:'Aaron Brok',score:0},
    ],
    top_2: [
        {name:'Chuppa Cross IV',score:1},
        {name:'Jiseok Lee',score:2},
    ],
    winner: 'Jiseok Lee',
    winningTeam: regionalTeam_01_08_2023,
}