export const gameNames = {
    "red-blue": "Red & Blue",
    yellow: "Yellow",
    gold: "Gold",
    silver: "Silver",
    'gold-silver': 'Gold & Silver',
    crystal: "Crystal",
    ruby: "Ruby",
    sapphire: "Sapphire",
    "ruby-sapphire": "Ruby & Sapphire",
    emerald: "Emerald",
    "ruby-sapphire-emerald": "Ruby, Sapphire & Emerald",
    "fire-red": "FireRed",
    "leaf-green": "LeafGreen",
    "fire-red-leaf-green": "FireRed & LeafGreen",
    diamond: "Diamond",
    pearl: "Pearl",
    platinum: "Platinum",
    "diamond-pearl": "Diamond & Pearl",
    "diamond-pearl-platinum": "Diamond, Pearl & Platinum",
    "diamond-platinum": "Diamond & Platinum",
    "heart-gold": "HeartGold",
    "soul-silver": "SoulSilver",
    "heart-gold-soul-silver": "HeartGold & SoulSilver",
    black: "Black",
    white: "White",
    "black-white": "Black & White",
    "black-2-white-2": "Black 2 & White 2",
    "black-white-black-2-white-2": "Black, White, Black 2 & White 2",
    x: "X",
    y: "Y",
    "x-y": "X & Y",
    "omega-ruby": "Omega Ruby",
    "alpha-sapphire": "Alpha Sapphire",
    "omega-ruby-alpha-sapphire": "Omega Ruby & Alpha Sapphire",
    "x-omega-ruby": "X & Omega Ruby",
    "y-alpha-sapphire": "y & Alpha Sapphire",
    sun: "Sun",
    moon: "Moon",
    'sun-moon': 'Sun & Moon',
    "ultra-sun": "Ultra Sun",
    "ultra-moon": "Ultra Moon",
    'ultra-sun-ultra-moon': 'Ultra Sun & Ultra Moon',
    "sun-ultra-sun": "Sun & Ultra Sun",
    "lets-go-pikachu-eevee": "Let's Go Pikachu & Eevee",
    sword: "Sword",
    shield: "Shield",
    'sword-shield': 'Sword & Shield',
    "shield-brilliant-diamond-shining-pearl": "Shield & BDSP",
    "brilliant-diamond": "Brilliant Diamond",
    "shining-pearl": "Shining Pearl",
    "brilliant-diamond-shining-pearl": "Brilliant Diamond & Shining Pearl",
    "legends-arceus": "Legends Arceus",
    scarlet: "Scarlet",
    violet: "Violet",
    'scarlet-violet': 'Scarlet & Violet',
};