export const movesDropDownScarletViolet = [
    'Absorb',
    'Accelerock',
    'Acid Armor',
    'Acid Spray',
    'Acid',
    'Acrobatics',
    'Acupressure',
    'Aerial Ace',
    'After You',
    'Agility',
    'Air Cutter',
    'Air Slash',
    'Ally Switch',
    'Amnesia',
    'Ancient Power',
    'Apple Acid',
    'Aqua Jet',
    'Aqua Ring',
    'Aqua Step',
    'Aqua Tail',
    'Arm Thrust',
    'Armor Cannon',
    'Aromatic Mist',
    'Astonish',
    'Attack Order',
    'Attract',
    'Aura Sphere',
    'Aurora Beam',
    'Aurora Veil',
    'Avalanche',
    'Axe Kick',
    'Baby-Doll Eyes',
    'Baneful Bunker',
    'Beat Up',
    'Belch',
    'Belly Drum',
    'Bind',
    'Bite',
    'Blast Burn',
    'Blizzard',
    'Block',
    'Body Press',
    'Body Slam',
    'Bone Rush',
    'Boomburst',
    'Bounce',
    'Brave Bird',
    'Breaking Swipe',
    'Brick Break',
    'Brine',
    'Brutal Swing',
    'Bubble Beam',
    'Bug Bite',
    'Bulk Up',
    'Bulldoze',
    'Bullet Punch',
    'Bullet Seed',
    'Charge Beam',
    'Charge',
    'Charm',
    'Chilling Water',
    'Circle Throw',
    'Clear Smog',
    'Close Combat',
    'Coil',
    'Collision Course',
    'Compuppance',
    'Confide',
    'Confuse Ray',
    'Confusion',
    'Copycat',
    'Cosmic Power',
    'Cotton Guard',
    'Cotton Spore',
    'Counter',
    'Covet',
    'Crabhammer',
    'Cross Chop',
    'Cross Poison',
    'Crunch',
    'Crush Claw',
    'Curse',
    'Dark Pulse',
    'Dazzling Gleam',
    'Defend Order',
    'Defense Curl',
    'Defog',
    'Destiny Bond',
    'Dig',
    'Disable',
    'Disarming Voice',
    'Discharge',
    'Dive',
    'Doodle',
    'Double Hit',
    'Double Kick',
    'Double Team',
    'Double-Edge',
    'Draco Meteor',
    'Dragon Breath',
    'Dragon Claw',
    'Dragon Dance',
    'Dragon Darts',
    'Dragon Pulse',
    'Dragon Rush',
    'Dragon Tail',
    'Drain Punch',
    'Draining Kiss',
    'Drill Peck',
    'Drill Run',
    'Dual Wingbeat',
    'Dynamic Punch',
    'Earth Power',
    'Earthquake',
    'Echoed Voice',
    'Eletric Terrain',
    'Electro Ball',
    'Electroweb',
    'Encore',
    'Endeavor',
    'Endure',
    'Energy Ball',
    'Entrainment',
    'Eruption',
    'Expanding Force',
    'Explosion',
    'Extrasensory',
    'Extreme Speed',
    'Facade',
    'Fairy Lock',
    'Fairy Wind',
    'Fake Out',
    'Fake Tears',
    'False Surrender',
    'False Swipe',
    'Feather Dance',
    'Feint',
    'Fell Stinger',
    'Fiery Dance',
    'Fillet Away',
    'Fire Blast',
    'Fire Lash',
    'Fire Pledge',
    'Fire Punch',
    'Fire Spin',
    'First Impression',
    'Flail',
    'Flame Charge',
    'Flame Wheel',
    'Flamethrower',
    'Flare Blitz',
    'Flash Cannon',
    'Flatter',
    'Fling',
    'Flip Turn',
    'Flower Trick',
    'Fly',
    'Flying Press',
    'Focus Blast',
    'Focus Energy',
    'Focus Punch',
    'Follow Me',
    'Foul Play',
    'Freeze-Dry',
    'Frenzy Plant',
    'Frost Breath',
    'Fury Attack',
    'Fury Cutter',
    'Fury Swipes',
    'Future Sight',
    'Gastro Acid',
    'Giga Acid',
    'Giga Drain',
    'Giga Impact',
    'Gigaton Hammer',
    'Glaive Rush',
    'Glare',
    'Grass Knot',
    'Grass Pledge',
    'Grassy Terrain',
    'Gravity',
    'Growl',
    'Growth',
    'Guard Split',
    'Gaurd Swap',
    'Guillotine',
    'Gunk Shot',
    'Gust',
    'Gyro Ball',
    'Hammer Arm',
    'Harden',
    'Haze',
    'Head Smash',
    'Headbutt',
    'Headlong Rush',
    'Heal Bell',
    'Heal Pulse',
    'Healing Wish',
    'Heat Wave',
    'Heavy Slam',
    'Helping Hand',
    'Hex',
    'High Horsepower',
    'High Jump Kick',
    'Hone Claws',
    'Horn Attack',
    'Howl',
    'Hurricane',
    'Hydro Cannon',
    'Hydro Pump',
    'Hyper Beam',
    'Hyper Drill',
    'Hyper Voice',
    'Hypnosis',
    'Ice Beam',
    'Ice Fang',
    'Ice Hammer',
    'Ice Punch',
    'Ice Shard',
    'Ice Spinner',
    'Icicle Crash',
    'Icicle Spear',
    'Icy Wind',
    'Imprison',
    'Incinerate',
    'Infestation',
    'Ingrain',
    'Instruct',
    'Iron Defense',
    'Iron Head',
    'Iron Tail',
    'Jaw Lock',
    'Jet Punch',
    'Knock Off',
    'Kowtow Cleave',
    'Last Resort',
    'Last Respects',
    'Lava Plume',
    'Leaf Blade',
    'Leaf Storm',
    'Leafage',
    'Leech Life',
    'Leech Seed',
    'Leer',
    'Lick',
    'Life Dew',
    'Light Screen',
    'Liquidation',
    'Lock-On',
    'Low Kick',
    'Low Sweep',
    'Lumina Crash',
    'Lunge',
    'Mach Punch',
    'Magic Powder',
    'Magic Room',
    'Magical Leaf',
    'Magnet Rise',
    'Magnetic Flux',
    'Mean Look',
    'Mega Drain',
    'Mega Kick',
    'Megahorn',
    'Memento',
    'Metal Burst',
    'Metal Claw',
    'Metal Sound',
    'Meteor Mash',
    'Metronome',
    'Milk Drink',
    'Mimic',
    'Minimize',
    'Mist',
    'Misty Terrain',
    'Moonblast',
    'Moonlight',
    'Morning Sun',
    'Mortal Spin',
    'Mud-Slap',
    'Muddy Water',
    'Mystical Fire',
    'Nasty Plot',
    'Night Shade',
    'Night Slash',
    'Noble Roar',
    'Nuzzle',
    'Order Up',
    'Overdrive',
    'Overheat',
    'Pain Split',
    'Parabolic Charge',
    'Parting Shot',
    'Payback',
    'Peck',
    'Perish Song',
    'Petal Blizzard',
    'Pin Missile',
    'Play Nice',
    'Play Rough',
    'Pluck',
    'Posion Fang',
    'Posion Gas',
    'Posion Jab',
    'Posion Powder',
    'Poison Sting',
    'Poison Tail',
    'Pollen Puff',
    'Population Bomb',
    'Pounce',
    'Pound',
    'Powder Snow',
    'Power Gem',
    'Power Split',
    'Power Swap',
    'Power Trick',
    'Power Trip',
    'Power Whip',
    'Present',
    'Protect',
    'Psych Up',
];

